myblog/blog/urls.py
from django.conf.urls import url

from blog.views import Index, Detail, About, Acticle, Comment, MoodList, Login, Reg, Quit

urlpatterns = [
    url(r'^$', Index.as_view(), name='主页'),
    url(r'^detail/(\d+)/$', Detail.as_view(), name='文章详情'),
    url(r'^about', About.as_view(), name='关于'),
    url(r'^acticle', Acticle.as_view(), name='成长'),
    url(r'^comment', Comment.as_view(), name='留言'),
    url(r'^moodList', MoodList.as_view(), name='说说'),
    url(r'^login', Login.as_view(), name='登录'),
    url(r'^reg', Reg.as_view(), name='注册'),
    url(r'^quit', Quit.as_view(), name='注销'),
]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 添加子路由
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

myblog/blog/models.py
from django.core.validators import RegexValidator
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class Article(models.Model):
    writer = models.CharField(max_length=20, verbose_name='发布者')
    title = models.CharField(max_length=50, verbose_name='标题')
    content = RichTextUploadingField(verbose_name='内容')
    read = models.SmallIntegerField(default=0, verbose_name='阅读量')
    comment = models.SmallIntegerField(default=0, verbose_name='评论数')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        verbose_name = '文章管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Label(models.Model):
    name = models.CharField(max_length=20, verbose_name='标签名')
    article = models.ManyToManyField(to='Article', verbose_name='文章')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        verbose_name = '标签管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Talk(models.Model):
    """说说"""
    content = models.CharField(max_length=255, verbose_name='说说')
    picture = models.ImageField(upload_to='talk/%Y%m/%d', verbose_name='说说图片', null=True)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        verbose_name = '说说管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content


class IndexPicture(models.Model):
    """首页轮播"""
    title = models.CharField(max_length=20, verbose_name='图片描述')
    picture = models.ImageField(upload_to='home/%Y%m', verbose_name='首页轮播图片')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        verbose_name = '首页轮播管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class MessageBoard(models.Model):
    content = models.CharField(max_length=255, verbose_name='留言内容')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')

    class Meta:
        verbose_name = '留言板管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content


class User(models.Model):
    phone = models.CharField(max_length=11,
                             verbose_name='手机号',
                             validators=[
                                 RegexValidator(r'^1[3-9]\d{9}$', "手机号码格式错误!")
                             ])
    password = models.CharField(max_length=32, verbose_name='密码')
    integral = models.SmallIntegerField(verbose_name='积分', default=0)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='注册时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.phone

myblog/blog/forms.py
from django import forms

from blog.helper import set_password
from blog.models import MessageBoard, User


class UserForm(forms.ModelForm):
    """用户注册验证"""
    # 单独添加字段
    password = forms.CharField(max_length=16,
                               min_length=6,
                               error_messages={
                                   'required': '密码不能为空',
                                   'max_length': '密码长度最大长度为16位',
                                   'min_length': '密码长度最小长度为6位'
                               })

    repassword = forms.CharField(error_messages={'required': '确认密码不能为空'})

    class Meta:
        model = User
        fields = ['phone', ]
        error_messages = {
            'phone': {
                'required': '手机号不能为空!'
            }
        }

    def clean_phone(self):
        # 验证手机号是否唯一
        phone = self.cleaned_data.get('phone')
        rs = User.objects.filter(phone=phone).exists()
        if rs:
            raise forms.ValidationError('手机号已被被注册!')
        else:
            return phone

    def clean(self):
        # 验证两次密码是否一致
        password = self.cleaned_data.get('password')
        repassword = self.cleaned_data.get('repassword')
        if password and repassword and password != repassword:
            raise forms.ValidationError({'repassword': '两次输入的密码不一致!'})


class LoginForm(forms.ModelForm):
    """用户登录验证"""

    class Meta:
        model = User
        fields = ['phone', 'password']
        error_messages = {
            'phone': {
                'required': '手机号不能为空!'
            },
            'password': {
                'required': '密码不能为空!'
            }
        }

    def clean(self):
        # 验证账号密码是否正确
        phone = self.cleaned_data.get('phone')
        password = self.cleaned_data.get('password')
        # 根据手机号获取
        try:
            user = User.objects.get(phone=phone)
        except User.DoesNotExist:
            raise forms.ValidationError({'phone': '手机号未被注册!'})
        # 验证密码
        if user.password != set_password(password):
            raise forms.ValidationError({'password': '密码错误!'})
        # 将用户信息保存到cleaned_data中
        self.cleaned_data['user'] = user
        return self.cleaned_data

myblog/blog/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views import View

from blog.forms import UserForm, LoginForm
from blog.helper import set_password, json_msg
from blog.models import Article, Label, Talk, MessageBoard, IndexPicture, User


class Login(View):
    """登陆"""

    def get(self, request):
        return render(request, 'blog/login.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        form = LoginForm(data)
        if form.is_valid():
            # 合法
            user = form.cleaned_data['user']
            # 保存session
            request.session['ID'] = user.pk
            request.session['phone'] = user.phone
            # 登录成功跳转到主页
            return redirect('blog:主页')
        else:
            # 不合法
            return render(request, 'blog/login.html', context=form.errors)


class Reg(View):
    """注册"""

    def get(self, request):
        return render(request, 'blog/reg.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        # 验证数据合法性
        form = UserForm(data)
        if form.is_valid():
            # 保存数据库
            user = User()
            user.phone = form.cleaned_data.get('phone')
            user.password = set_password(form.cleaned_data.get('password'))
            user.save()
            # 跳转到登录
            return redirect('blog:登录')
        else:
            return render(request, 'blog/reg.html', context=form.errors)


class Index(View):
    """首页"""

    def get(self, request):
        # 操作数据
        pictures = IndexPicture.objects.filter(is_delete=False)
        # 获取文章按发布时间排序
        add_articles = Article.objects.filter(is_delete=False).order_by('-add_time')
        # 获取文章按阅读量排序
        read_articles = Article.objects.filter(is_delete=False).order_by('-read')
        # 获取标签
        labels = Label.objects.filter(is_delete=False)
        context = {
            'add_articles': add_articles,
            'read_articles': read_articles,
            'labels': labels,
            'pictures': pictures
        }
        return render(request, 'blog/index.html', context=context)


class Detail(View):
    """文章详情页"""

    def get(self, request, id):
        article = Article.objects.get(pk=id)
        # 获取文章按发布时间排序
        add_articles = Article.objects.filter(is_delete=False).order_by('-add_time')
        context = {
            'article': article,
            'add_articles': add_articles
        }
        return render(request, 'blog/article_detail.html', context=context)


class About(View):
    """关于"""

    def get(self, request):
        return render(request, 'blog/about.html')


class Acticle(View):
    """成长"""

    def get(self, request):
        articles = Article.objects.filter(is_delete=False)
        # 获取文章按发布时间排序
        add_articles = Article.objects.filter(is_delete=False).order_by('-add_time')
        context = {
            'add_articles': add_articles,
            'articles': articles
        }
        return render(request, 'blog/article.html', context=context)


class Comment(View):
    """留言"""

    def get(self, request):
        messages = MessageBoard.objects.all().order_by('-add_time')
        context = {
            'messages': messages
        }
        return render(request, 'blog/comment.html', context=context)

    def post(self, requset):
        # 接收参数
        data = requset.POST
        content = data['content']
        # 操作数据库
        MessageBoard.objects.create(content=content)
        return JsonResponse(json_msg(0, '留言成功'))


class MoodList(View):
    """说说"""

    def get(self, request):
        # 获取说说数据
        talks = Talk.objects.filter(is_delete=False)
        context = {
            'talks': talks
        }
        return render(request, 'blog/moodList.html', context=context)


class Quit(View):
    """注销登录"""

    def get(self, request):
        # 删除session
        request.session.flush()
        return redirect('blog:登录')

myblog/templates/blog/about.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    关于
{% endblock %}

{% block head_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}"/>
{% endblock %}

{% block head_js %}
    <script type="text/javascript" src="{% static 'plugin/jquery.page.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="w_header">
        <div class="container">
            <div class="w_header_top">
                {#            <a href="#" class="w_logo"></a>#}
                <span class="w_header_nav">
					<ul>
						<li><a href="{% url 'blog:主页' %}">首页</a></li>
						<li><a href="{% url 'blog:关于' %}" class="active">关于</a></li>
						<li><a href="{% url 'blog:成长' %}">成长</a></li>
						<li><a href="">学习</a></li>
						<li><a href="">娱乐</a></li>
						<li><a href="{% url 'blog:说说' %}">说说</a></li>
						<li><a href="{% url 'blog:留言' %}">留言</a></li>
                        <li><a href=""></a></li>
                        <li><a href=""></a></li>
                        {% if request.session.ID %}
                            <li><a href="">{{ request.session.phone }}</a></li>
                            <li><a href="">退出登录</a></li>
                        {% else %}
                            <li><a href="{% url 'blog:登录' %}" title="登录">登录</a></li>
                            <li><a href="{% url 'blog:注册' %}" title="注册">注册</a></li>
                        {% endif %}
					</ul>
				</span>
                <div class="w_search">
                    <div class="w_searchbox">
                        <input type="text" placeholder="search"/>
                        <button>搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="w_container">
        <div class="container">
            <div class="row w_main_row">

                <ol class="breadcrumb w_breadcrumb">
                    <li><a href="#">首页</a></li>
                    <li class="active">关于我</li>
                    <span class="w_navbar_tip">像“草根”一样，紧贴着地面，低调的存在，冬去春来，枯荣无恙。</span>
                </ol>

                <div class="col-lg-9 col-md-9 w_main_left" style="height: 1000px;">
                    <div class="about">
                        <h2>Just about me</h2>
                        <ul>
                            <p>空白，不代表没有，只是因为还未准备好。。。</p>
                            <p>看了很多博主的帖子，我深受鼓舞。想到自己当年大学刚入学，老师要求我们几人一组做一个网站。那个时候我们都是0基础，很多人傻乎乎的不知如何入手。时间是一个月的时间，我几乎是天天泡在图书馆，晚上11点宿舍断电，我就抱着电脑去旁边的咖啡厅通宵。没用20天的时间，我一个人，几乎看扁了所有图书馆有关PS，DW，FLASH等的书籍，粗糙的做出了属于自己的第一个网站。虽然不是那么整齐，也不是那么美观，但是我一个人做到了，老师也很惊讶。大学毕业后各种压力让我不得不放弃当初的梦想。工作碌碌无为，不是没有精神，而是觉得自己只是一个喘气的人，而不是一个为了一个目标而活着的人。几次拿起早就尘封了多年的网站设计类书本，但是迫于生活无奈又放下。多少次纠结。直到今天无意中看到博主的文章，让我心里一震。一辈子也就是几十年的时间吧，如果不能把自己无限的精力投入到有限的青春中，追寻自己的梦，那么活着和喘气又有什么区别</p>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 w_main_right">
                    <div class="about_c">
                        <p>昵称：<span>Messi</span> | 嘟狗</p>
                        <p>姓名：黄伟 </p>
                        <p>生日：1995-03-08</p>
                        <p>邮箱：775984360@qq.com</p>
                        <p>籍贯：四川省—南充市</p>
                        <p>现居：四川省—成都市</p>
                        <p>职业：Python全栈工程师</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myblog/templates/blog/article.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    成长
{% endblock %}

{% block head_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}"/>
    <link rel="stylesheet" href="{% static 'plugin/jquery.page.css' %}">
{% endblock %}

{% block head_js %}
    <script src="{% static 'js/common.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="w_header">
        <div class="container">
            <div class="w_header_top">
                <span class="w_header_nav">
					<ul>
						<li><a href="{% url 'blog:主页' %}">首页</a></li>
						<li><a href="{% url 'blog:关于' %}">关于</a></li>
						<li><a href="{% url 'blog:成长' %}" class="active">成长</a></li>
						<li><a href="">学习</a></li>
						<li><a href="">娱乐</a></li>
						<li><a href="{% url 'blog:说说' %}">说说</a></li>
						<li><a href="{% url 'blog:留言' %}">留言</a></li>
                        <li><a href=""></a></li>
                        <li><a href=""></a></li>
                        {% if request.session.ID %}
                            <li><a href="">{{ request.session.phone }}</a></li>
                            <li><a href="">退出登录</a></li>
                        {% else %}
                            <li><a href="{% url 'blog:登录' %}" title="登录">登录</a></li>
                            <li><a href="{% url 'blog:注册' %}" title="注册">注册</a></li>
                        {% endif %}
					</ul>
				</span>
                <div class="w_search">
                    <div class="w_searchbox">
                        <input type="text" placeholder="search"/>
                        <button>搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="w_container">
        <div class="container">
            <div class="row w_main_row">

                <ol class="breadcrumb w_breadcrumb">
                    <li><a href="#">首页</a></li>
                    <li class="active">文章</li>
                    <span class="w_navbar_tip">我们长路漫漫，只因学无止境。</span>
                </ol>

                <div class="col-lg-9 col-md-9 w_main_left">
                    <div class="panel panel-default">
                        <div class="panel-body contentList">
                            {% for article in articles %}
                                <div class="panel panel-default w_article_item">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3">
                                                <a href="#" class="thumbnail w_thumbnail">
                                                    <img src="{% static 'image/头像.png' %}" alt="...">
                                                </a>
                                            </div>

                                            <h4 class="media-heading">
                                                <a class="title" href="{% url  'blog:文章详情' article.pk %}">{{ article.title }}</a>
                                            </h4>
                                            <p>
                                                {% for label in article.label_set.all %}
                                                    <a class="label label-default">{{ label.name }}</a>
                                                {% endfor %}
                                            </p>
                                            <p class="w_list_overview overView">{{ article.content | truncatewords:4 |safe }}</p>
                                            <p class="count_r"><span class="count">
                                                <i class="glyphicon glyphicon-user"></i>
                                                <a href="#">{{ article.writer }}</a></span>
                                                <span class="count">
                                                    <i class="glyphicon glyphicon-eye-open"></i>阅读:{{ article.read }}
                                                </span>
                                                <span class="count">
                                                    <i class="glyphicon glyphicon-comment"></i>评论:{{ article.comment }}
                                                </span><span
                                                        class="count"><i class="glyphicon glyphicon-time"></i>{{ article.update_time }}</span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                </div>

                <div class="col-lg-3 col-md-3 w_main_right">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">最新发布</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-unstyled sidebar">
                                {% for add_article in add_articles %}
                                    <li><a href="/post/04928311">{{ add_article.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">友情链接</h3>
                        </div>
                        <div class="panel-body">
                            <div class="newContent">
                                <ul class="list-unstyled sidebar shiplink">
                                    <li><a href="https://www.baidu.com/" target="_blank">百度</a></li>
                                    <li><a href="https://www.oschina.net/" target="_blank">开源中国</a></li>
                                    <li><a href="http://www.ulewo.com/" target="_blank">有乐网</a></li>
                                    <li><a href="http://www.sina.com.cn/" target="_blank">新浪网</a></li>
                                    <li><a href="http://www.qq.com/" target="_blank">腾讯网</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

myblog/templates/blog/article_detail.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    {{ article.title }}
{% endblock %}
{% block head_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/article_detail.css' %}"/>
{% endblock %}
{% block head_js %}
    <script src="{% static 'js/common.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="w_header">
        <div class="container">
            <div class="w_header_top">
                {#            <a href="#" class="w_logo"></a>#}
                <span class="w_header_nav">
					<ul>
						<li><a href="{% url 'blog:主页' %}">首页</a></li>
						<li><a href="{% url 'blog:关于' %}">关于</a></li>
						<li><a href="{% url 'blog:成长' %}">成长</a></li>
						<li><a href="">学习</a></li>
						<li><a href="">娱乐</a></li>
						<li><a href="{% url 'blog:说说' %}">说说</a></li>
						<li><a href="{% url 'blog:留言' %}">留言</a></li>
                        <li><a href=""></a></li>
                        <li><a href=""></a></li>
                        {% if request.session.ID %}
                            <li><a href="">{{ request.session.phone }}</a></li>
                            <li><a href="">退出登录</a></li>
                        {% else %}
                            <li><a href="{% url 'blog:登录' %}" title="登录">登录</a></li>
                            <li><a href="{% url 'blog:注册' %}" title="注册">注册</a></li>
                        {% endif %}
					</ul>
				</span>
                <div class="w_search">
                    <div class="w_searchbox">
                        <input type="text" placeholder="search"/>
                        <button>搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="w_container">
        <div class="container">
            <div class="row w_main_row">

                <ol class="breadcrumb w_breadcrumb">
                    <li><a href="{% url 'blog:主页' %}">首页</a></li>
                    <li><a href="{% url 'blog:成长' %}">文章</a></li>
                    <li class="active">{{ article.title }}</li>
                    <span class="w_navbar_tip">我们长路漫漫，只因学无止境。</span>
                </ol>

                <div class="col-lg-9 col-md-9 w_main_left">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h2 class="c_titile">{{ article.title }}</h2>
                            <p class="box_c"><span class="d_time">发布时间：{{ article.add_time }}</span>
                                <span>编辑：<a href="">{{ article.writer }}</a></span>
                                <span>阅读：{{ article.read }}</span></p>

                            <ul class="infos">
                                {{ article.content |safe }}
                            </ul>

                            <div class="keybq">
                                <p><span>关键字</span>：
                                    {% for foo in article.label_set.all %}
                                        <a class="label label-default">{{ foo.name }}</a>
                                    {% endfor %}
                                </p>
                            </div>


                            <div class="nextinfo">
                                <p class="last">上一篇：<a href="#">免费收录网站搜索引擎登录口大全</a></p>
                                <p class="next">下一篇：<a href="#">javascript显示年月日时间代码</a></p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 w_main_right">

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">最新发布</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-unstyled sidebar">
                                {% for add_article in add_articles %}
                                    <li><a href="{% url 'blog:文章详情' add_article.pk %}">{{ add_article.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">友情链接</h3>
                        </div>
                        <div class="panel-body">
                            <div class="newContent">
                                <ul class="list-unstyled sidebar shiplink">
                                    <li><a href="https://www.baidu.com/" target="_blank">百度</a></li>
                                    <li><a href="https://www.oschina.net/" target="_blank">开源中国</a></li>
                                    <li><a href="http://www.ulewo.com/" target="_blank">有乐网</a></li>
                                    <li><a href="http://www.sina.com.cn/" target="_blank">新浪网</a></li>
                                    <li><a href="http://www.qq.com/" target="_blank">腾讯网</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
{% endblock %}
{% block footer_js %}
    <div id="shape">
        <div class="shapeColor">
            <div class="shapeFly">
            </div>
        </div>
    </div>
{% endblock %}

myblog/templates/blog/comment.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    留言
{% endblock %}

{% block head_js %}
    <script type="text/javascript" src="{% static 'plugin/jquery.page.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="w_header">
        <div class="container">
            <div class="w_header_top">
                {#            <a href="#" class="w_logo"></a>#}
                <span class="w_header_nav">
					<ul>
						<li><a href="{% url 'blog:主页' %}">首页</a></li>
						<li><a href="{% url 'blog:关于' %}">关于</a></li>
						<li><a href="{% url 'blog:成长' %}">成长</a></li>
						<li><a href="">学习</a></li>
						<li><a href="">娱乐</a></li>
						<li><a href="{% url 'blog:说说' %}">说说</a></li>
						<li><a href="{% url 'blog:留言' %}" class="active">留言</a></li>
                        <li><a href=""></a></li>
                        <li><a href=""></a></li>
                        {% if request.session.ID %}
                            <li><a href="">{{ request.session.phone }}</a></li>
                            <li><a href="{% url 'blog:注销' %}">退出登录</a></li>
                        {% else %}
                            <li><a href="{% url 'blog:登录' %}" title="登录">登录</a></li>
                            <li><a href="{% url 'blog:注册' %}" title="注册">注册</a></li>
                        {% endif %}
					</ul>
				</span>
                <div class="w_search">
                    <div class="w_searchbox">
                        <input type="text" placeholder="search"/>
                        <button>搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="w_container">
        <div class="container">
            <div class="row w_main_row">
                <ol class="breadcrumb w_breadcrumb">
                    <li><a href="{% url 'blog:主页' %}">首页</a></li>
                    <li class="active">留言</li>
                    <span class="w_navbar_tip">你，生命中最重要的过客，之所以是过客，因为你未曾为我停留。</span>
                </ol>

                <div class="col-lg-9 col-md-9 w_main_left">
                    <form action="{% url 'blog:留言' %}" method="post">
                        {% csrf_token %}
                        <p style="color: red">{{ errors.content.0 }}</p>
                        <textarea rows="3" name="content" id="content" class="form-control"></textarea>
                        <br/>
                        <input type="hidden" id="session" value="{{ request.session.ID }}">
                        <input class="btn btn-success" id="sbt" type="button" value="留言">
                    </form>
                    <br/>
                    {% for message in messages %}
                        <div>
                            <p style="font-size: 18px;font-family:'宋体','仿宋',sans-serif;">{{ message.content }}</p>
                            <p style="text-align:right;">留言时间：{{ message.add_time }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_js %}
    <script>
        $(function () {
            //判断用户是否登录,登录才能留言
            $('#sbt').on('click', function () {
                var id = $('#session').val();
                var content = $("#content").val();
                var data = {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'content': content
                }
                console.debug(content)
                if (id) {
                    if (content) {
                        $.ajax({
                            url: '{% url "blog:留言" %}',
                            type: 'post',
                            data: data,
                            dataType: 'json',
                            success: function (data) {
                                alert('留言成功');
                                location.href = "{% url 'blog:留言' %}";
                            }
                        })
                    } else {
                        alert('留言内容不能为空');
                    }
                } else {
                    alert('请登录后留言');
                }
            });
        })
    </script>
{% endblock %}