myblog/blog/urls.py
from django.conf.urls import url

from blog.views import Index, Detail, About, Acticle, Comment, MoodList, Login, Reg, Quit

urlpatterns = [
    url(r'^$', Index.as_view(), name='主页'),
    url(r'^detail/(\d+)/$', Detail.as_view(), name='文章详情'),
    url(r'^about', About.as_view(), name='关于'),
    url(r'^acticle', Acticle.as_view(), name='成长'),
    url(r'^comment', Comment.as_view(), name='留言'),
    url(r'^moodList', MoodList.as_view(), name='说说'),
    url(r'^login', Login.as_view(), name='登录'),
    url(r'^reg', Reg.as_view(), name='注册'),
    url(r'^quit', Quit.as_view(), name='注销'),
]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 添加子路由
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

myblog/templates/common/parent.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            嘟狗个人博客
        {% endblock %}
    </title>
    <link href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}"/>
    <link href="{% static 'image/logo.ico' %}" rel="shortcut icon"/>
    <script src="{% static 'plugin/jquery.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>

    {% block head_css %}
        {#      写css      #}
    {% endblock %}

    {% block head_js %}
        {#      写js     #}
    {% endblock %}
</head>

<body>
{% block header %}
    <div class="w_header">
        <div class="container">
            <div class="w_header_top">
                {#            <a href="#" class="w_logo"></a>#}
                <span class="w_header_nav">
					<ul>
						<li><a href="{% url 'blog:主页' %}" class="active">首页</a></li>
						<li><a href="{% url 'blog:关于' %}">关于</a></li>
						<li><a href="{% url 'blog:成长' %}">成长</a></li>
						<li><a href="">学习</a></li>
						<li><a href="">娱乐</a></li>
						<li><a href="{% url 'blog:说说' %}">说说</a></li>
						<li><a href="{% url 'blog:留言' %}">留言</a></li>
                        <li><a href=""></a></li>
                        <li><a href=""></a></li>
                        {% if request.session.ID %}
                            <li><a href="">{{ request.session.phone }}</a></li>
                            <li><a href="{% url 'blog:注销' %}">退出登录</a></li>
                        {% else %}
                            <li><a href="{% url 'blog:登录' %}" title="登录">登录</a></li>
                            <li><a href="{% url 'blog:注册' %}" title="注册">注册</a></li>
                        {% endif %}
					</ul>
				</span>
                <div class="w_search">
                    <div class="w_searchbox">
                        <input type="text" placeholder="search"/>
                        <button>搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    <div class="w_foot">
        <div class="w_foot_copyright">Copyright &copy; 2017-2020, www.wfyvv.com. All Rights Reserved. <span>|</span>
            <a target="_blank" href="http://www.miitbeian.gov.cn/" rel="nofollow">皖ICP备17002922号</a>
        </div>
    </div>
{% endblock %}

{% block footer_js %}

{% endblock %}

</body>
</html>